### ISSUE TITLE
Year of the output date is incorrect in results

### ISSUE THREAD

**Issue by bryce-carson** [KrishnamurthyLab/spatialEpisim.foundation#5]
```
   Date            N     S
   <date>      <dbl> <dbl>
 1 4200-02-07 814366     0
 2 4200-02-05 814337    29
 3 4200-02-05 814309    57
 4 4200-02-04 814280    86
 5 4200-02-03 814251   114
 6 4200-02-02 814223   143
 7 4200-02-01 814194   171
 8 4200-02-01 814165   199
 9 4200-01-31 814137   228
10 4200-01-30 814108   256
```

@kle6951, please learn enough of [the _lubridate_ package](https://lubridate.tidyverse.org/index.html) to hack on the new code in the `leftover-spaghetti-casserole` branch and fix the apparent issue exampled above. I haven't pushed the updated code you need to GitHub yet, but I'll do that very soon, then you can start on this issue if you want to work on "core" code.

The exampled results are from the tibble (a better dataframe class) output by the [SVEIRD.BayesianDataAssimilation](https://krishnamurthylab.github.io/spatialEpisim.foundation/reference/SVEIRD.BayesianDataAssimilation.html) function.

**Comment by kle6951** [comment]
Okay, I'll take a look once I and Tobias finish our on-going issue.

**Comment by bryce-carson** [comment]
@kle6951 The updated code was pushed this afternoon. You can start on this when you're able to.
